[package]
name = "ftml_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "ftml_py"
crate-type = ["cdylib"]

[dependencies]

pyo3 = { version = "0.20.0", features = ["extension-module"] }

ftml = { path = "C:/Users/dell/Desktop/wikidot_edit_resh-1/rust_engine/ftml" }